import { doAllCalculations } from "./functions";
import { SumOfNumbers } from "./functions";
import { genPassword } from "./functions";
import { getRandomArray } from "./functions";
import { getSubjects } from "./functions";
import { student } from "./functions";
import {} from "./functions";
import {} from "./functions";
import {} from "./functions";
import {} from "./functions";
